services:
  web:
    build: .
    command: python /last/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/last
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DB_HOST: db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres